// GENERATED by tool/build_unicode_fallback_fonts.py - do not edit.
// Ordered exactly like the fallback chain: earlier entries win.
// Regenerate with: python3 tool/build_unicode_fallback_fonts.py
// Families are NOT declared in pubspec.yaml: the web/wasm engine preloads
// every FontManifest entry at startup. Runtime code probes system
// fallback coverage, then loads only the matching plain asset.
class UnicodeFallbackFontAsset {
  const UnicodeFallbackFontAsset(this.family, this.asset);

  final String family;
  final String asset;
}

const List<UnicodeFallbackFontAsset> kUnicodeFallbackFontAssets =
    <UnicodeFallbackFontAsset>[
      UnicodeFallbackFontAsset(
        'Noto Color Emoji',
        'assets/font/NotoColorEmoji.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Emoji',
        'assets/font/ufs/NotoEmoji-Regular.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u00001',
        'assets/font/ufs/PlangothicP1_u00001.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u0E001',
        'assets/font/ufs/PlangothicP1_u0E001.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u18800',
        'assets/font/ufs/PlangothicP1_u18800.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u20000',
        'assets/font/ufs/PlangothicP1_u20000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u20741',
        'assets/font/ufs/PlangothicP1_u20741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u20E82',
        'assets/font/ufs/PlangothicP1_u20E82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u215C3',
        'assets/font/ufs/PlangothicP1_u215C3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u21D04',
        'assets/font/ufs/PlangothicP1_u21D04.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u22000',
        'assets/font/ufs/PlangothicP1_u22000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u22741',
        'assets/font/ufs/PlangothicP1_u22741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u22E82',
        'assets/font/ufs/PlangothicP1_u22E82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u235C3',
        'assets/font/ufs/PlangothicP1_u235C3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u23D04',
        'assets/font/ufs/PlangothicP1_u23D04.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u24000',
        'assets/font/ufs/PlangothicP1_u24000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u24741',
        'assets/font/ufs/PlangothicP1_u24741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u24E82',
        'assets/font/ufs/PlangothicP1_u24E82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u255C3',
        'assets/font/ufs/PlangothicP1_u255C3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u25D04',
        'assets/font/ufs/PlangothicP1_u25D04.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u26000',
        'assets/font/ufs/PlangothicP1_u26000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u26741',
        'assets/font/ufs/PlangothicP1_u26741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u26E82',
        'assets/font/ufs/PlangothicP1_u26E82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u275C3',
        'assets/font/ufs/PlangothicP1_u275C3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u27D04',
        'assets/font/ufs/PlangothicP1_u27D04.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u28000',
        'assets/font/ufs/PlangothicP1_u28000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u28741',
        'assets/font/ufs/PlangothicP1_u28741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u28E82',
        'assets/font/ufs/PlangothicP1_u28E82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u295C3',
        'assets/font/ufs/PlangothicP1_u295C3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u29D04',
        'assets/font/ufs/PlangothicP1_u29D04.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2A000',
        'assets/font/ufs/PlangothicP1_u2A000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2A761',
        'assets/font/ufs/PlangothicP1_u2A761.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2AEA2',
        'assets/font/ufs/PlangothicP1_u2AEA2.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2B5E3',
        'assets/font/ufs/PlangothicP1_u2B5E3.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2BD25',
        'assets/font/ufs/PlangothicP1_u2BD25.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2C000',
        'assets/font/ufs/PlangothicP1_u2C000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2C741',
        'assets/font/ufs/PlangothicP1_u2C741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2CE82',
        'assets/font/ufs/PlangothicP1_u2CE82.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2D5C5',
        'assets/font/ufs/PlangothicP1_u2D5C5.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2DD06',
        'assets/font/ufs/PlangothicP1_u2DD06.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2E000',
        'assets/font/ufs/PlangothicP1_u2E000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2E741',
        'assets/font/ufs/PlangothicP1_u2E741.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P1 u2F833',
        'assets/font/ufs/PlangothicP1_u2F833.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u00295',
        'assets/font/ufs/PlangothicP2_u00295.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0A66E',
        'assets/font/ufs/PlangothicP2_u0A66E.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0B39C',
        'assets/font/ufs/PlangothicP2_u0B39C.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0BB9F',
        'assets/font/ufs/PlangothicP2_u0BB9F.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0C000',
        'assets/font/ufs/PlangothicP2_u0C000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0C803',
        'assets/font/ufs/PlangothicP2_u0C803.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0D006',
        'assets/font/ufs/PlangothicP2_u0D006.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u0E21D',
        'assets/font/ufs/PlangothicP2_u0E21D.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u1236F',
        'assets/font/ufs/PlangothicP2_u1236F.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u16100',
        'assets/font/ufs/PlangothicP2_u16100.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u176F8',
        'assets/font/ufs/PlangothicP2_u176F8.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u17EFB',
        'assets/font/ufs/PlangothicP2_u17EFB.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u18000',
        'assets/font/ufs/PlangothicP2_u18000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u18806',
        'assets/font/ufs/PlangothicP2_u18806.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u1AFF0',
        'assets/font/ufs/PlangothicP2_u1AFF0.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u1CC00',
        'assets/font/ufs/PlangothicP2_u1CC00.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u1E000',
        'assets/font/ufs/PlangothicP2_u1E000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u30000',
        'assets/font/ufs/PlangothicP2_u30000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u30803',
        'assets/font/ufs/PlangothicP2_u30803.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u31006',
        'assets/font/ufs/PlangothicP2_u31006.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u3180F',
        'assets/font/ufs/PlangothicP2_u3180F.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u32000',
        'assets/font/ufs/PlangothicP2_u32000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u32803',
        'assets/font/ufs/PlangothicP2_u32803.otf',
      ),
      UnicodeFallbackFontAsset(
        'Plangothic P2 u33007',
        'assets/font/ufs/PlangothicP2_u33007.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u00100',
        'assets/font/ufs/SourceHanSansSC_u00100.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u02012',
        'assets/font/ufs/SourceHanSansSC_u02012.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u03697',
        'assets/font/ufs/SourceHanSansSC_u03697.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u03EC6',
        'assets/font/ufs/SourceHanSansSC_u03EC6.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u04000',
        'assets/font/ufs/SourceHanSansSC_u04000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u04834',
        'assets/font/ufs/SourceHanSansSC_u04834.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u05100',
        'assets/font/ufs/SourceHanSansSC_u05100.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u059BD',
        'assets/font/ufs/SourceHanSansSC_u059BD.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u06000',
        'assets/font/ufs/SourceHanSansSC_u06000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u06883',
        'assets/font/ufs/SourceHanSansSC_u06883.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u07114',
        'assets/font/ufs/SourceHanSansSC_u07114.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u079B1',
        'assets/font/ufs/SourceHanSansSC_u079B1.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u08000',
        'assets/font/ufs/SourceHanSansSC_u08000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u088A6',
        'assets/font/ufs/SourceHanSansSC_u088A6.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u09114',
        'assets/font/ufs/SourceHanSansSC_u09114.otf',
      ),
      UnicodeFallbackFontAsset(
        'Source Han Sans SC u09998',
        'assets/font/ufs/SourceHanSansSC_u09998.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Unicode u00008',
        'assets/font/ufs/NotoUnicode_u00008.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Unicode u0200B',
        'assets/font/ufs/NotoUnicode_u0200B.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Unicode u10000',
        'assets/font/ufs/NotoUnicode_u10000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Unicode u12000',
        'assets/font/ufs/NotoUnicode_u12000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Unicode u1D000',
        'assets/font/ufs/NotoUnicode_u1D000.otf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Sans Living u00700',
        'assets/font/ufs/NotoSansLiving_u00700.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Sans Living u0219A',
        'assets/font/ufs/NotoSansLiving_u0219A.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Sans Living u0A000',
        'assets/font/ufs/NotoSansLiving_u0A000.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Sans Living u1D400',
        'assets/font/ufs/NotoSansLiving_u1D400.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Noto Sans Historical u01680',
        'assets/font/ufs/NotoSansHistorical_u01680.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Kreative Square u02072',
        'assets/font/ufs/KreativeSquare_u02072.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UFSTemp Alpha u16D80',
        'assets/font/ufs/UFSTempAlpha_u16D80.otf',
      ),
      UnicodeFallbackFontAsset(
        'UFSZero Ext u02800',
        'assets/font/ufs/UFSZeroExt_u02800.otf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaFunky u0E003',
        'assets/font/ufs/UnicodiaFunky_u0E003.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u13460',
        'assets/font/ufs/UnicodiaSesh_u13460.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u135AD',
        'assets/font/ufs/UnicodiaSesh_u135AD.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u136FA',
        'assets/font/ufs/UnicodiaSesh_u136FA.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u1385A',
        'assets/font/ufs/UnicodiaSesh_u1385A.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u139C8',
        'assets/font/ufs/UnicodiaSesh_u139C8.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u13B4C',
        'assets/font/ufs/UnicodiaSesh_u13B4C.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u13CCB',
        'assets/font/ufs/UnicodiaSesh_u13CCB.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u13E53',
        'assets/font/ufs/UnicodiaSesh_u13E53.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u13FD0',
        'assets/font/ufs/UnicodiaSesh_u13FD0.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u14000',
        'assets/font/ufs/UnicodiaSesh_u14000.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u1416F',
        'assets/font/ufs/UnicodiaSesh_u1416F.ttf',
      ),
      UnicodeFallbackFontAsset(
        'UnicodiaSesh u142F5',
        'assets/font/ufs/UnicodiaSesh_u142F5.ttf',
      ),
      UnicodeFallbackFontAsset(
        'NewGardiner u0E45B',
        'assets/font/ufs/NewGardiner_u0E45B.ttf',
      ),
      UnicodeFallbackFontAsset(
        'Xdareg(darage)v1(RL) u11380',
        'assets/font/ufs/Xdaregdaragev1RL_u11380.otf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D000',
        'assets/font/ufs/TempSeal_u3D000.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D0AB',
        'assets/font/ufs/TempSeal_u3D0AB.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D156',
        'assets/font/ufs/TempSeal_u3D156.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D201',
        'assets/font/ufs/TempSeal_u3D201.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D2AC',
        'assets/font/ufs/TempSeal_u3D2AC.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D357',
        'assets/font/ufs/TempSeal_u3D357.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D402',
        'assets/font/ufs/TempSeal_u3D402.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D4AD',
        'assets/font/ufs/TempSeal_u3D4AD.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D558',
        'assets/font/ufs/TempSeal_u3D558.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D603',
        'assets/font/ufs/TempSeal_u3D603.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D6AE',
        'assets/font/ufs/TempSeal_u3D6AE.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D759',
        'assets/font/ufs/TempSeal_u3D759.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D804',
        'assets/font/ufs/TempSeal_u3D804.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D8AF',
        'assets/font/ufs/TempSeal_u3D8AF.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3D95A',
        'assets/font/ufs/TempSeal_u3D95A.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DA05',
        'assets/font/ufs/TempSeal_u3DA05.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DAB0',
        'assets/font/ufs/TempSeal_u3DAB0.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DB5B',
        'assets/font/ufs/TempSeal_u3DB5B.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DC06',
        'assets/font/ufs/TempSeal_u3DC06.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DCB1',
        'assets/font/ufs/TempSeal_u3DCB1.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DD5C',
        'assets/font/ufs/TempSeal_u3DD5C.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DE07',
        'assets/font/ufs/TempSeal_u3DE07.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DEB2',
        'assets/font/ufs/TempSeal_u3DEB2.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3DF5D',
        'assets/font/ufs/TempSeal_u3DF5D.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E000',
        'assets/font/ufs/TempSeal_u3E000.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E0AB',
        'assets/font/ufs/TempSeal_u3E0AB.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E156',
        'assets/font/ufs/TempSeal_u3E156.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E201',
        'assets/font/ufs/TempSeal_u3E201.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E2AC',
        'assets/font/ufs/TempSeal_u3E2AC.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E357',
        'assets/font/ufs/TempSeal_u3E357.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E402',
        'assets/font/ufs/TempSeal_u3E402.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E4AD',
        'assets/font/ufs/TempSeal_u3E4AD.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E558',
        'assets/font/ufs/TempSeal_u3E558.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E603',
        'assets/font/ufs/TempSeal_u3E603.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E6AE',
        'assets/font/ufs/TempSeal_u3E6AE.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E759',
        'assets/font/ufs/TempSeal_u3E759.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E804',
        'assets/font/ufs/TempSeal_u3E804.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E8AF',
        'assets/font/ufs/TempSeal_u3E8AF.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3E95A',
        'assets/font/ufs/TempSeal_u3E95A.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EA05',
        'assets/font/ufs/TempSeal_u3EA05.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EAB0',
        'assets/font/ufs/TempSeal_u3EAB0.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EB5B',
        'assets/font/ufs/TempSeal_u3EB5B.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EC06',
        'assets/font/ufs/TempSeal_u3EC06.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3ECB1',
        'assets/font/ufs/TempSeal_u3ECB1.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3ED5C',
        'assets/font/ufs/TempSeal_u3ED5C.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EE07',
        'assets/font/ufs/TempSeal_u3EE07.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EEB2',
        'assets/font/ufs/TempSeal_u3EEB2.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3EF5D',
        'assets/font/ufs/TempSeal_u3EF5D.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F008',
        'assets/font/ufs/TempSeal_u3F008.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F0B3',
        'assets/font/ufs/TempSeal_u3F0B3.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F15E',
        'assets/font/ufs/TempSeal_u3F15E.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F209',
        'assets/font/ufs/TempSeal_u3F209.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F2B4',
        'assets/font/ufs/TempSeal_u3F2B4.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F35F',
        'assets/font/ufs/TempSeal_u3F35F.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F40A',
        'assets/font/ufs/TempSeal_u3F40A.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F4B5',
        'assets/font/ufs/TempSeal_u3F4B5.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F560',
        'assets/font/ufs/TempSeal_u3F560.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F60B',
        'assets/font/ufs/TempSeal_u3F60B.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F6B6',
        'assets/font/ufs/TempSeal_u3F6B6.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F761',
        'assets/font/ufs/TempSeal_u3F761.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F80C',
        'assets/font/ufs/TempSeal_u3F80C.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F8B7',
        'assets/font/ufs/TempSeal_u3F8B7.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3F962',
        'assets/font/ufs/TempSeal_u3F962.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3FA0D',
        'assets/font/ufs/TempSeal_u3FA0D.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3FAB8',
        'assets/font/ufs/TempSeal_u3FAB8.ttf',
      ),
      UnicodeFallbackFontAsset(
        'TempSeal u3FB63',
        'assets/font/ufs/TempSeal_u3FB63.ttf',
      ),
    ];

// Delta/length/asset-index triples encoded as unsigned LEB128, then
// base64. Decoded lazily on the first non-ASCII text scan.
const String kUnicodeFallbackFontRangeIndexBase64 =
    'AAAAAAYCAAFTAAICAAAAABECAAAAAAECAAAAAAUCAAAAAAQCAAkAAG4CAAAAAAMCAAAAAFACAANDAAtT'
    'AANDAAVTAAFDAAtTAAACAABDAAACAABDAAACAABTAAACAABTAAACAABTAAACAA9TAAFDAAFTAAFDAAJT'
    'AANDAAFTAAFDABNTAAVDACNTAABDAANTAAACAAdTAAFDAAxTAAFDABtTAAFDAAACAAxDABpTAAFDAA1T'
    'AAACAABTAAACAEVTAABDAA5TAABDADJTAAArABtTAAArAARTAAArAAFTAABDAApTAABDAABTAAJDAAxT'
    'AABDAAZTAAArAABTAAArAAVTAAFDABNTAAFDAAFTAABDAAFTAAArAANTAABDABVTAAArACpTAAArACdT'
    'AgVTBAVTAAACAQBTAQJTAAdDAAACAAdDAQZDAAACAAVTAABDAAArAAdDAAArAA1DACpTAAArAApTAABD'
    'AAFTAAArAABTAAECAAdTAD9DAABTAABDAG1TAAACAA1TAAACAF9TASVTAQArAAZTAAACAClTAAErAAJT'
    'ATZTAAErBhpTBAVTCwRTAAArABZTAAArAAhTAAErAABTAAErAANTAAArAAVTAAErAAdTAAArAABTAAEr'
    'AChTAAArADFTAAArAF1TAA1YATtYAgJYAC9TADFYDjpYAgIrAC1TAg5TARtTAgBTAQorBSErBQgrAABT'
    'AAArAApTADYrABpTAAArAIMBUwAAKwAHUwIBUwIVUwEGUwEAUwMDUwIIUwIBUwIDUwgAUwQBUwEEUwIY'
    'UwAAKwECUwEFUwQBUwIVUwEGUwEBUwEBUwEBUwIAUwEEUwQBUwICUwMAUwcDUwEAUwcQUwoCUwEIUwEC'
    'UwEVUwEGUwEBUwEEUwIJUwECUwECUwIAUw8DUwILUwcEKwAAUwAAKwECUwEHUwIBUwIVUwEGUwEBUwEE'
    'UwIIUwIBUwICUwUBKwACUwQBUwEEUwIRUwoBWAEFWAMCWAEDWAMBWAEAWAEBWAMBWAMCWAMLWAQEWAMC'
    'WAEDWAIAWAYAWA4UWAUMUwECUwEWUwEPUwIAKwAHUwECUwEDUwcBUwECUwEBKwIDUwIJUwcVUwECUwEW'
    'UwEJUwEEUwIIUwECUwEDUwcBUwUBKwAAUwEDUwIJUwECUwwMUwECUwEyUwECUwEFUwQPUwIZUwECUwER'
    'UwMXUwEIUwEAUwIGUwMAUwQFUwEAUwEHUwYJUwICUww5WAQcWCUBUwEAUwEAKwABUwAAKwAAUwEAKwAA'
    'UwAFKwADUwAAKwAGUwAAKwACUwEAUwEAUwABKwABUwAAKwAMUwAAKwACUwIEUwEAUwEFUwAAKwEJUwID'
    'UyAKUwAAKwAAUwAAKwAqUwAAKwAFUwAHKwEjKwQMKwABUwAAKwAOUwAAKwAGUwEYUwABKwAIUwEOUwEM'
    'UyXFAVgBAFgFAFgCL1gA/wErAEhYAQNYAgZYAQBYAQNYAihYAQNYAiBYAQNYAgZYAQBYAQNYAg5YAThY'
    'AQNYAkJYAh9YAxlYBlVYAgVYAv8EWAAcXANQUwAHKwcMUwAAKwAGUwAAKwkAKwAWUwkTUwwMUwECUwEB'
    'UwwzWAABKwAnWAIJWAYJWAYOUwAAKwAJUwZXUwABKwYqUwVFWAocUwABKwELUwQLUwQAUwMLUwAdWAIE'
    'WAsrWAQZWAYKWAM9WAIBWAA+UwEcUwIKUwYJUwYNUwIOUwAxKw9LUwAAKwEBKwAsUwACKwBzUwg7UwMO'
    'UwMCUwAvWAAKKwUqWAICWAAHUwgpUwAAKwU0UwAAAgAMUwAAKwAEUwABKwAGUwAAKwACUwAAKwAKUwAA'
    'KwA4UwAAKwABUwAAKwAFUwABAgAIUwABKwBCUwAFKwAvUwAAAgAAUwAAAgAOUwABQwBfUwAnQwAAAgAA'
    'QwAAAgAuQwAbUwIFUwIXUwAHAgAFUwIFUwIHUwEAUwEAUwEAUwEeUwI0UwEOUwENUwIBUwADAgESUwIC'
    'UwEIUwEKKwAAVAAAKwAAAAADKwAARAABKwABRAAAVAABAgAARAAAVAABAgAARAAAVAABKwAARAABVAAA'
    'RAAAKwAARAAHKwAARAAAVAABRAAAVAAARAACVAACRAAAAAAEVAAARAADVAABRAAAAAAGVAAARAAMVAAF'
    'KwEJKwABVAABXQAARAAZVAAEKwAGVAAAKwAAVAACKwAIVAAARAAAVAABRAASVAAEKwsMVAABRAADVAAA'
    'AAAMVA8ARAABVAAARAAAVAAARAACVAABRAADVAAARAACVAAARAABVAAARAAJVAAARAAAAAACVAABRAAC'
    'VAAARAABVAAARAAFVAAARAACVAAAAAAAVAAARAAHVAAAKwAaVAALRAADVAALRAANVAABKwQDRAAFAAAO'
    'WQABAAAMWQABRAAJWQACRAADWQABRAACWQAARAAAWQAARAAAWQAARAAQWQADRAAKWQAARAAJWQAARAAA'
    'WQABRAAAWQAGRAACWQAARAAAWQACRAAAWQAARAADWQAARAABWQADRAABWQAARAAAWQAJRAAEWQADRAAE'
    'WQAARAAEWQAARAAAWQAARAABWQAARAACWQAARAAEWQAARAAMWQACRAAAWQADRAABWQABRAABWQABRAAB'
    'WQABRAABWQABRAAJWQAFRAABWQABRAAIWQAERAAFWQAARAADWQAARAAYWQAARAAZWQABRAASWQAARAAP'
    'WQAEVAACRAAJVAAARAAEVAAARAAAVAABAAALVAAAAAABRACEAVQAAUQAC1QADkQAAFQAAEQAAAAACVQA'
    'AUQADFQACgAAAysAAgAABCsAIQIABysWCl0VYUQAAAAA5gFEAAEAAARZAAJEAAFZAAAAAABEAANZAAFE'
    'AAFZAAAAAABEAANZAAZEAABZAAVEAA1ZAAREAAdZAABEAApZAAMAAABZAAQAAAFEAgBEAANZAAAAAABE'
    'AABdAAAAAABdAABZAAEAAAFEAAAAAwBEAAAAAAFEAAAAAABZAAEAAAFZAAAAAAJZAAAAAAJZAAEAAAdd'
    'AAIAAARZAAAAAABEAAAAAARZAAsAAAoCAAEAAAFEAAAAAABEAAEAAABEAAAAAAZEAAFZAAhEAAAAAAFE'
    'AAEAAAlZAAVdAAFZAAUAAABZAAAAAABZAAEAAABZAgEAAARZAAAAAAFZAAEAAANZAAEAAApZAAEABQEA'
    'AgAABQEAAQAAAQEADQZZAAEAAARZAAUAAABZAAMAAAFZAAAAAAFZAAArAQAAAgAAAgUAAABdAAAAAABd'
    'AQAAAABEAAAAAABdAAAAAABdAgBEAgAAAAJZAAAABgAAAQBZCAEAAQBZAgBZAwBEAQFEAwAAAgAABAAA'
    'AQAAAANdAAIAAABEAAAACwEADQFZAh1EAQIAAwBZBQAAAAJdCwAADgAAAD9ZAABf/wEzWQABAACIAVkA'
    'AEQAOVkAAUQAgwJZAARUAAIAABFUAABEAAEAAC9UAAArAAFUAAAAAANUAAAAAAlUABMrAokBKwAuVAAA'
    'KwAuVAAAKwAfVABzWQUsWQEAWQUAWQI3WQcBWQ4XWQkGWQEGWQEGWQEGWQEGWQEGWQEGWQEGWQFZVAAB'
    'RAAGVAAaKwIDKxwZAgFYAgzVAQIaCysAAwIAAUQAACsAA0QACisAAUQABysADUQAAysAAUQAAAAAC0QA'
    'AAAAAUQBVUQCZkQFKkQBXSsBK0QAAwIAEUQAAAIAEEQAAQIJAAIAD0QAHisBP0QAHisAF0QAAAAAAEQA'
    'AAAAkQFEAAArAIQCRAAAKwACRAAAKwCJAUQAAAIAHEQAAAIAD0QAAAIAFEQAAAIAC0QAAAIACUQAAAIA'
    'HkQAAAIArwJEAAACACZEAJcDRQAAAgBLRQAAAgC8AUUAAAIAsAJFAAACACVFAAACACxFAAACAEJFAAAC'
    'AElFAAACAEtFAAACAPUBRQAAAgBnRQAAAgAeRQAAAgAURQAAAgA5RQAAAgAmRQAAAgCnAUUAAAIAa0UA'
    'AAIAGEUAuQJGADhHAAACAKgBRwAAAgDCAkcAAAIAPUcAAAIAmQFHAAACAFZHAAACAHpHAAACAAJHAAAC'
    'ADBHAAACAENHAAACABxHAAACAENHAAACAHZHAAACABtHAAACAARHAAACAA1HAAACAAJHAAACALICRwAA'
    'AgAnRwAAAgAHRwAAAgB/RwAAAgBnRwAAAgCBAUcAU0gAAAIAVUgAAAIA5wFIAAACAKwBSAAAAgAnSAAA'
    'AgARSAAAAgA4SAAAAgC5AUgAAAIAJUgAAAIAcUgAAAIAYEgAAAIASEgAAAIAxwFIAAkCQAACAAArAAFI'
    'AAArAAFIAAErAANIAAACAAArAAJIAAACAAVIAAArAABIAAArAAtIAAACAANIAAArAANIAAACAAJIAAAC'
    'AAArAAECAABIAAArAAJIAAACAABIAAACAAErAABIAAArAABIAAArAAxIAAACAAJIAAICAABIAAArAANI'
    'AAACABBIAAECAABIAAACAAdIAAACAABIAAACAAFIAAECAARIAAACAAJIAAACAApIAAACAAhIAAArAAFI'
    'AAArAANIAAACAApIAAECAANIAAACAANIAAArAAJIAAArAAJIAAArAAFIAAACAABIAAArAABIAAErAABI'
    'AAErAABIAAArAARIAAArAAJIAAACAANIAAArABNIAAACAA9IAAArAA1IAAArAA5IAAACAAFIAAACAD5I'
    'AAACABNIAAACAANIAAACACFIAAACAAtIAAACAAJIAAACABVIAAACAApIAAACABNIAAACABdIAAACABJI'
    'AAACAAVIAAACAAxIAAACACJIAAACABJIAAACAAdIAAACAABIAAACAAlIAAACADNIAAACAANIAAACABdI'
    'AAACAARIAAACAAVIAAACABRIAAACAAFIABVJAAACABBJAAACABVJAAECAANJAAACAAhJAAACABdJAAEC'
    'AABJAAErAAACAARJAAArAA1JAAACAABJAAArABBJAAACAAtJAAACAARJAAACAABJAAACAABJAAACAAhJ'
    'AAACABBJAAACAAFJAAACAA5JAAACAAJJAAACAAArAA9JAAACAAZJAAArAARJAAACAABJAAACAANJAAAC'
    'AA5JAAACABBJAAACAA9JAAACABJJAAACABJJAAECAAFJAAACAAlJAAACAARJAAACABBJAAACAAdJAAAC'
    'AAdJAAACAAZJAAACABFJAAECAAtJAAACAAFJAAACAABJAAACAAdJAAACAApJAAACAARJAAACAA9JAAAC'
    'AAJJAAECAAdJAAACAAJJAAACAAxJAAACAABJAAACAAJJAAACAAFJAAACAAhJAAECABRJAAACAABJAAAC'
    'AAVJAAArAARJAAArAAFJAAACAAlJAAACAAZJAAACAANJAAACAApJAAACAAtJAAACADJJAAArAAJJAAAr'
    'AAdJAAACAANJAAArAABJAAACABdJAAACAABJAAACAAxJAAArAA9JAAArAAlJAAACAANJAAACAANJAAAC'
    'AAJJAAACABhJAAECAAhJAAACAABJAAACAAJJAAECAFNJAAACAB1JAAACAAxJAAACADNJAAACABBJAAAC'
    'AD9JAAACAAtJAAACACJJAAACAAFJAAACAANJAAACAA9JAAACACFJAAACAABJAAACABxJAAACAABJAAAC'
    'ACJJAAACAFNJAAACAAtJAAACACZJAAACAA5JAAACACRJAAACAA9JAAACABpJAAACAARJAAACABRJAAAC'
    'AAVJAAACAAdJAAACAAArAAJJAAErAABJAAArAA1JAAArAABJAAACAH9JAAACAJ8BSQAAAgACSQAAAgAQ'
    'SQAAAgAJSQAAAgArSQAAAgAuSQAAAgAFSQAAAgAASQAAAgAISQAAAgAGSQAAAgAASQAAAgAESQAAAgAC'
    'SQAAAgABSQAAAgARSQAAAgABSQAAAgABSQAAAgAFSQAAAgADSQAAAgAASQABKwAASQAAKwABSQAAKwAA'
    'SQAAKwADSQAAAgACSQABKwABSQAAKwAISQAAAgAHSQAAAgAdSQAAAgABSQAAAgAgSQAAAgAESQAAAgAg'
    'SQBpSgAAAgAGSgAAAgAOSgAAAgAlSgAAAgAKSgAAAgAZSgAAAgCnAUoAAAIABkoAAAIAEEoAAAIAAEoA'
    'AAIACkoAAAIAD0oAAAIADUoAAAIABUoAAAIAYEoAAAIABUoAAAIAA0oAAAIAA0oAAAIABUoAAAIADkoA'
    'AAIAEUoAAQIACUoAAAIABkoAAAIAAEoAAAIABUoAAAIAGkoAAAIABUoAAAIAAEoAAQIAB0oAAAIAAUoA'
    'ACsAP0oAAAIADEoAAAIAV0oAAAIAKEoAAQIACkoAAAIAKkoAAAIABUoAAAIANUoAAAIAHUoAAAIAAEoA'
    'AAIACEoAAAIACkoAAAIAAEoAAAIABkoAAAIAAEoAAQIAASsAJkoAAAIACEoAAAIAJUoAAAIABUoAAAIA'
    'EEoAAAIAACsAAAIAAUoAAAIAAUoAAAIAKkoAAAIAIUoAAAIAB0oAAQIAF0oAAAIAD0oAAQIAACsAA0oA'
    'AAIAA0oAAAIAAEoAAAIACUoAAAIAE0oAAQIAEEoAAAIAAUoAAAIAAkoAAAIACUoAAQIADkoAAAIAD0oA'
    'AQIAFkoAAAIAAkoAAAIAGEoAAAIACkoAAAIADEoAAQIAL0oAAAIAAkoAAAIABUoAEUsAAAIACEsAAAIA'
    'G0sAAAIAVUsAAAIAAksAAAIAE0sAAAIANksAAAIAAksAAAIAXUsAAAIADksAAAIAOEsAAAIAAEsAAAIA'
    'DksAAAIAT0sAAAIAA0sAAAIACEsAAAIABksAAAIAJEsAAAIABksAAAIAE0sAAQIAOUsAAAIAJ0sAAAIA'
    'F0sAAAIABEsAAAIAAksAAQIAKEsAAAIAFUsAAAIAZEsAAAIABksAAAIAG0sAAAIAE0sAAAIAQEsAAAIA'
    'AUsAAAIAJksAAQIAREsAAAIAE0sAAAIAGksAAAIAAUsAAAIAJUsAAAIACUsAAAIAGksAAAIAIUsAAAIA'
    'AEsAAAIAHUsAAAIAA0sAAQIAGEsAAAIABUsAAAIADUsAAAIABUsAAAIACksAAQIABksAAAIABEsAACsA'
    'AEsAAAIADEsAAgIACUsAAAIAH0sAAAIAGUsAAQIAAksAAAIAF0sAAAIAE0sAAAIABksAAAIAVEsAAAIA'
    'AUsAAAIAEksAAAIAJUsAAAIAA0sAAAIAEEsAAAIAFksAAAIAEEsAAAIAAksAAAIABUsAAAIAA0sAAAIA'
    'BUsAAQIADUsAAAIAAksAAAIABEsAAAIABUsAAAIAJEsAAAIAACsAEksAAAIAFEsAAAIAAEsAAAIAGksA'
    'AAIAAksAAAIAVksAAAIAIksAAAIAB0sAAAIABEsAAAIAEksAAAIAG0sAAAIAA0sAAAIAI0sAAAIAAEsA'
    'AUwAAAIACkwAAAIAFUwAAAIAEUwAAAIAX0wAAAIASUwAAAIAOkwAAAIAEEwAAAIAJkwAAAIACkwAAAIA'
    'F0wAAQIADkwAAAIAGUwAAAIAAEwAAAIABUwAAAIAHkwAAAIAGkwAAAIAM0wAAAIAJUwAAAIAAkwAAAIA'
    'L0wAAAIAGkwAAQIAAkwAAAIABEwAAAIAJ0wAAAIABEwAAAIABkwAAAIAACsABEwAAAIABEwAAAIABUwA'
    'AQIAAEwAAQIAAUwAAAIAIEwAAAIAC0wAAAIAAEwAAAIAAUwAAAIAAEwAAAIABUwAAAIAEUwAAQIAC0wA'
    'AAIAAkwAAAIADUwAAAIAG0wAAAIAAUwAAAIAAUwAAAIAAUwAAAIAHkwAAQIACkwAACsAG0wAACsAKEwA'
    'AAIABEwAAAIAJ0wAAAIAE0wAAAIAF0wAAAIANEwAAAIAAUwAAAIAIUwAAQIAJkwAAAIAC0wAAQIAUUwA'
    'AAIADUwAAAIADkwAAAIAF0wAAAIABEwAAAIAH0wAAAIAFkwAAAIAHUwAAAIAC0wAAAIAEEwAAAIAE0wA'
    'AAIABUwAAAIAHEwAAAIAFUwAAAIAPEwAAAIAEUwAAQIAMEwAAAIAIkwAAAIAMEwAAAIAEkwAAAIAKkwA'
    'AAIABUwAAAIABUwAAAIAA0wAAQIADUwAAAIADkwAAAIAEUwAAAIAFEwAAAIAIkwAAQIAA0wAAAIAAUwA'
    'AAIAFUwAAAIABkwAAAIABEwAAAIACEwAAAIACEwAAAIAFkwAAQIAAEwAAAIAAkwAAQIAA0wAAAIABUwA'
    'AAIANEwAAAIAA0wACk0AAAIAB00AAAIAAk0AAAIADE0AAQIABU0AAAIAAE0AAAIAA00AAAIAAk0AAAIA'
    'AE0AAAIAA00AAAIAAk0AAAIABU0AAAIADU0AAAIAAE0AAAIAB00AAAIAAU0AAAIAA00AAQIAGE0AAAIA'
    'Hk0AAQIAB00AAAIABk0AAAIAAE0AAAIAEk0AAAIAAk0AAAIAGU0AAAIAAE0AAAIACE0AAQIACU0AAAIA'
    'AU0AAAIAA00AAAIAAk0AAQIAAE0AAQIAB00AAQIACE0AAAIABk0AAAIAAU0AAAIAD00AAAIABU0AAAIA'
    'PU0AAAIACU0AAQIAAk0AAAIADU0AAAIAA00AAAIANU0AAAIALE0AAAIAEE0AAAIAHU0AAAIAFk0AAAIA'
    'AE0AAAIAEE0AAAIAAE0AAAIAAE0AACsAAE0AACsAFU0AAAIABU0AACsABU0AAAIAKk0AAAIAEU0AAAIA'
    'E00AAAIAAU0AAAIAF00AAAIAEk0AAAIAFE0AAAIAEU0AAAIAB00AAQIAHk0AAAIADU0AAAIAfk0AAAIA'
    'BU0AAAIAB00AAAIABk0AAAIAACsAJk0AAAIACk0AAAIACU0AAAIAA00AAAIAFE0AAAIAVU0AAAIAO00A'
    'AAIAIU0AAAIAJU0AAAIAC00AAAIABU0AAAIAL00AAAIAD00AAAIAAE0AAAIAB00AAAIADk0AAAIAC00A'
    'AAIABU0AAAIABE0AAAIAC00AAAIADE0AAAIAL00AAAIAP00AAAIAE00AAAIANk0AAAIAC00AAAIABU0A'
    'AAIABk0AAAIAB00AAAIAAE0AACsAWE0AAAIAGk0AAAIABU0AAAIAGE0AAAIAA00AAAIAN00AAAIAAE0A'
    'AAIAIk0AAAIACU0AAAIAGU0AAAIABU0AAAIABE0AAAIABU0AAAIAD00AAAIAQk0AAAIALU0AAAIAAU0A'
    'DE4AAAIAAk4AAAIAA04AAAIAAU4AAAIAH04AAAIAL04AAAIADE4AAAIAAE4AAAIAEk4AAAIAG04AAAIA'
    'FU4AACsAC04AAAIALk4AAAIAGE4AAAIAD04AAAIAG04AAAIAAU4AAAIAA04AAAIAF04AAAIAAU4AAAIA'
    'AU4AAAIAIE4AAAIAAE4AAAIADU4AAAIADk4AAAIABU4AAAIADE4AAAIAAE4AAAIABk4AAAIAH04AAAIA'
    'FU4AAAIABE4AAAIAFk4AAAIACE4AAAIAEk4AAAIAA04AAAIAAE4AAAIAAE4AAAIACU4AAAIAEU4AAAIA'
    'Fk4AAAIAB04AAAIAIE4AAAIAEU4AAAIADU4AAAIACk4AAAIAAk4AAAIAGU4AAAIAIU4AAAIABE4AAAIA'
    'Ak4AAAIAC04AAgIADk4AAAIAFU4AAAIAEE4AAAIAC04AAAIAKk4AAAIAQ04AAAIAHE4AAAIANE4AAAIA'
    'E04AAAIALE4AAAIACE4AAAIAXE4AAAIAmwFOAAACABVOAAACAA9OAAACABNOAAACAApOAAACAAFOAAAC'
    'AABOAAACAA5OAAACAGROAABPAAECAAFPAAACAAJPAAACAAFPAAACAAVPAAACAB5PAAACAAtPAAACAARP'
    'AAACABhPAAACAA1PAAECAAJPAAACAAhPAAICAAdPAAICAANPAAACAANPAAACAAdPAAACAA1PAAACAAFP'
    'AAArAABPAAACABVPAAACAAZPAAACABBPAAACABJPAAACAAZPAAArAAJPAAACABBPAAACAAJPAAACAA9P'
    'AAACAAdPAAECAAZPAAACAANPAAECAABPAAACABBPAAACAARPAAACAARPAAACAAhPAAACADZPAAECAARP'
    'AAACAB5PAAACAANPAAACAAFPAAACAANPAAACAA5PAAACAABPAAACAAFPAAACAA1PAAACABBPAAACAAVP'
    'AAACAABPAAACAFZPAAACAAFPAAACAAVPAAACAAFPAAACAABPAAArAAJPAAArAAFPAAACAAJPAAArAABP'
    'AAACAAlPAAArAAVPAAECABFPAAACAAJPAAACAAxPAAACAAFPAAACAA5PAAACAA1PAAECAApPAAACAAFP'
    'AAACAAFPAAACAAJPAAACAAxPAAACAA1PAAACAAVPAAACAAFPAAACAAFPAAACAA5PAAACAAdPAAACAABP'
    'AAACAAhPAAACACdPAAACAAtPAAACAAhPAAACAANPAAACAAVPAAACAAtPAAACAAhPAAECAARPAAACAA1P'
    'AAACAANPAAMCAAlPAAACAANPAAACABNPAAACAEpPAAACAApPAAACAAxPAAACAJUBTwAAAgAMTwAAAgBS'
    'TwAAAgB7TwAAAgAATwAAAgApTwAAAgAKTwAAAgAlTwAAAgAQTwAAAgAMTwABAgAHTwAAAgADTwABAgAM'
    'TwAAAgDYAU8AAAIAMk8AAAIAC08AAAIAMk8AAAIAJU8AAAIAE08AAAIAAE8AAAIAJU8AAAIAH08AAAIA'
    'Ck8AAAIAFk8AAAIAQE8AG1AAAAIAC1AAAAIABlAAAAIABVAAAAIAAVAAAAIAFVAAAAIAFlAAAAIAC1AA'
    'AAIAEVAAAAIAMlAAAAIAGVAAAAIAClAAAAIAA1AAAAIABFAAAAIAEFAAAAIAF1AAAAIAD1AAAAIA1gFQ'
    'AAACABNQAAACAApQAAACAAVQAAACAAJQAAACACBQAAACAARQAAACAAFQAAACADZQAAACAB1QAAACACZQ'
    'AAACAB5QAAACAAFQAAArAJIBUAAAAgANUAAAAgAAUAAAAgALUAAAAgAMUAAAAgATUAAAAgAjUAAAAgAj'
    'UAAAAgAEUAAAAgAJUAAAAgAzUAAAAgATUAAAAgBFUAAAAgAKUAABAgAEUAAAAgA6UAAAAgAWUAAAAgAY'
    'UAAAAgAIUAAAAgCpAVAAAAIAD1AAACsABFAAAAIAAlAAAAIAB1AAAAIABlAAAQIAAVAAAAIAQFAAAAIA'
    'GFAAAAIAAlAAAAIAD1AAAAIAD1AAAAIAFFAAAAIAAlAAAAIASFAAAAIAA1AAAQIABFAAAAIAWlAAAAIA'
    'CVAAAAIAE1AAAAIAPVAAAAIAA1AAAAIAEVAAAAIAAFAAAAIAAVAAAAIAM1AAAAIAE1AAAAIAMVAAAAIA'
    'AVAAIlEAAAIACVEAAAIAA1EAAQIADVEAAAIAEVEAAAIASFEAAAIAEFEAAAIABFEAAAIAAVEAAAIAAFEA'
    'AAIACFEAAAIABFEAAAIAGFEAAQIAH1EAAAIAAFEAAAIAC1EAAAIABlEAAAIAAlEAAAIACVEAAAIAAlEA'
    'AAIAEFEAAAIADVEAAAIAKFEAAAIAC1EAAAIADFEAAAIAVVEAAAIAMVEAAAIAAlEAAAIADVEAAAIAI1EA'
    'AAIADlEAAAIAeFEAAAIAB1EAAAIAFlEAAAIABVEAAAIAN1EAAAIAAFEAAAIAJlEAAQIA8AFRAAECAAVR'
    'AAECAAhRAAACACFRAAACAAhRAAACAC9RAAACADJRAAECAA9RAAACABtRAAACAABRAAACACZRAAACAAFR'
    'AAACAABRAAACAABRAAACAAFRAAACAAVRAAACABtRAAACAA1RAAACAAJRAAECAClRAAECAANRAAACAAxR'
    'AAECADlRAAACABRRAAACAARRAAACAAFRAAECAAJRAAACAApRAAACAAVRAAACAApRAAACAE9RAAACAA9R'
    'AAACAAJRAAACAAlRAAACAAVRAAACABJRAAACABVRAAACAABRAAACAAlRAAACABRRAAACACFRAAACABVR'
    'AAACADNRAAECACFRAAACAAtRAAACAAFRAAICAAxRAAACABpRAAACABRRAAACAEFRAAACADFRAAACAABR'
    'AABSAAACAAxSAAACAANSAAACABhSAAACAABSAAACACdSAAACAAtSAAACAAhSAAACAAlSAAACAFVSAAAC'
    'AABSAAACADpSAAACAGhSAAACABFSAAACAAhSAAACAAtSAAACAAdSAAACABNSAAACABNSAAACACNSAAAC'
    'ACZSAAACABBSAAACADRSAAACAFFSAAACACNSAAACAGdSAAACACdSAAACAAFSAAACAE9SAAACAAFSAAAC'
    'AJMBUgAAAgAhUgACAgBUUgAAAgABUgAAAgAFUgAAAgAWUgAAAgAGUgAAAgADUgACAgAbUgABAgAHUgAB'
    'AgABUgAAAgAqUgABAgAOUgAAAgADUgAAAgA7UgAAAgAtUgAAAgAMUgAAAgAKUgAAAgABUgAAAgABUgAB'
    'AgAEUgAAAgAAUgABAgABUgAAAgAAUgAAAgADUgAAAgAHUgAAAgACUgAAAgABUgABAgACUgAAAgAAUgAA'
    'AgAaUgABAgABUgAAAgACUgARAgCMCVoDNloJ2wJaFC1UAAAsAC5UAAAsAFhUCB9aAI0BVAAvLAQALA4F'
    'LAA0VAAALAMJVAY3XAhEVAAALAgLVAYdVAABLABTVAsAVAAcLANNWgEKWgQRWgAALAANWgE2VAkNVAIJ'
    'VAIDVAAfWgBCVBgbVAoFWgIFWgIFWgkGWgEGWgEvVAADLAABVAAHLAJ9WgIJWgabDywAghAtACAuAAAC'
    'AL4ILgCCEC8AghAwAJ0PMQwWMQQwMYUQAQMAAGAADgMBDgNBAQPIAQIDDQEDAQIDEwADBgADqgEAAwEB'
    'AwQAAwsAMgKpAgMCAwMBDAMBHQMBBQMBJQMBCAMBBQMBPgMBAAMBAQMBBQMBBQMBBwMBJwMBAgMBAAMB'
    'AgMBAQMBAgMBBwMABG0AJQMAAG0ADAMAAG0AcwMBDQMBCAMBKwMBTwMBBAMCNgMCBAMBFgMBAAOAAl8D'
    'BCQDAQwDAVIDAhIDHQAy4gsFXQAFMgABXQAAMgATXQABMgAEXQAAMgAEXQAAMgAIXQAAMgAAXQAAMgAa'
    'XQAAMgADXQAAMgDhAV0AMQMAAF0AbAMAAF0AMQMAAF0AAAMAAF0AIgMAAF0AAQMAtQFdDlVdqgGDA10A'
    'AFQAngFdugIBXWBfXWAfXWCfA10wGV0GDl0AAFQA7QIDAmkDJgRSAAFUAABdCwRUBRlUAQRUAQBUAQFU'
    'AQFUAXtUABAyAGNUAAAyANcCVAABMgA1VAAGMgAAVCANVAAPMgABAQAJUgYNVAABMgAiUgESUgEDUgQE'
    'VAEWVAAAMgAAVAAAMgAEVAAAMgACVAAAMgAQVAAAMgAUVAAAMgACVAAAMgAKVAAAMgAGVAAAMgACVAAA'
    'MgAeVAIAVAGeAVIAHjIDBTICBTICBTICAjIDBlIBBlIBA10FAjIAAVQCC1UBGVUBElUBAVUBDlUCDVUi'
    'elUFAlUELFUDU1UAAzIBDFUDAFUvLVWCARxcAzBcDxsyBB5VAAAyAANVCQJVABpcBSpVBR1cASRcBA1c'
    'Kn9cAB1aAglaBiNaBCNaBCdVCDMyCwsyAQ4yAQYyAQEyAQoyAQ4yAQYyAQEyAzMyDLYCVQkVVQoHVRgF'
    'MgEpMgENMkAFXAIAXAErXAEBXAMAXAIWXAEIXAA+VQgIVTASVQEBVQUEVQAbXAMaXAUAXAAcMiM3VQQT'
    'VQIxVQEBVQUHVQECVQEaVQABMgICVQQIVQAAMgcIVQcfXAAfVSAmVQQLVQk1VQMGVQAVXAIaXAUHXAAR'
    'MgcDMgwGMlBGXAAAMgAAXDcyMg0yMgcFMgAnVQgJVQYYYAAAMgALYAMAYAAFMgAVYAgBMtABHjIBKVUB'
    'AlUCAVUQBTIBJTIBNzIIKTIWGTImGzIUFjIJTVUEHVUABTIJADIAQVUAADIKADICGFoHCVoGNFUBEFUA'
    'ADIIJjIJTVUAATIAD1UBE1ULEVUBK1UAAjI+BlUBAFUBA1UBDlUBClUGOjIFCTIGA1UBB1UCAVUCFVUB'
    'BlUBAVUBBFUBCVUCAVUCAlUCAFUGAFUFBlUCBlUDBFULCW4BAG4CAG4BJW4BCW4BAG4CAG4BA24BCW4B'
    'AW4IAW4dWVUAADIAAFUBAFUAAzIeRzIICTKmATUyAiUyIkQyCwkyBgwyEzhVAAAyBglVBhMyHBlVAAAy'
    'Ag5VBA9VAAYyuQE7VWRSVQwAVQAGMgIAMgIHMgEBMgEdMgEBMgILMgkJMkYHMgItMgIKMhtGMgAAVQhS'
    'VQ1IVQcKMlUHMlghMg4JMgYIVQEsVQENVQocVQMfVQIVVQENVUkGVQEBVQErVQMAVQEBVQEIVQgJVQYF'
    'VQEBVQEkVQEBVQEFVQcJVQYrMgQJMvYBGDIHEDIBKDIBADIBHDJVADIPMTINADIA7gZWACozZmJcAAwz'
    'AANcAM8BMwy2AjOJEmIzDa4IVgAmMwrMAmEAzAJiAFdjAABtAABjAABtAAdjAABtAAFjAABtACJjAABt'
    'AAVjAABtAD5jAABtACljAABtAARjAAJtAAFjAAJtAAJjAABtAABjAABtAA9jAABtAA5jAABtAAFjAABt'
    'ACtjAAhkAABtAClkAAFtABhkAABtAAJkAABtABdkAAFtAAVkAABtAAFkAABtAAZkAABtAAZkAABtAABk'
    'AAFtAAJkAABtAA9kAABtAA1kAABtAANkAAJtABpkAAFtAB9kAABtAEJkAABtAARkAAFtAABkAABtABdk'
    'AANtAARkAABtAANkAABtAAJkAABtAAFkAAFlAABtAANlAABtAABlAABtAAJlAAJtAAVlAABtAAplAABt'
    'AA1lAABtAAJlAABtAABlAABtAAVlAABtAABlAAFtAAllAABtAANlAAFtAAJlAAFtAABlAABtABRlAABt'
    'AC1lAABtAAxlAABtAAZlAABtAANlAABtAABlAAFtAAdlAABtAAJlAAJtAAhlAABtABllAAFtABZlAABt'
    'AAJlAAFtAAJlAABtAAZlAAFtAAFlAAFtAAZlAABtAA5lAABtAA1lAABtAAJlAABtAAplAABtAABlAAFt'
    'AANlAABtAAllAABtAAFlAAFtAARlAABtAA1lAABtAABlAABmAABtAABmAABtABBmAABtAAtmAABtAAFm'
    'AABtAARmAABtACpmAABtAAlmAABtAAlmAABtAAJmAABtAABmAAFtAAdmAABtAAdmAABtAABmAAFtAANm'
    'AABtAAxmAABtAABmAABtAAhmAABtAA1mAAFtAA1mAAFtAARmAABtACNmAABtABlmAABtAAFmAABtABNm'
    'AAFtAABmAAJtAAJmAABtAAJmAABtAANmAABtAAhmAAFtAAJmAAFtAAFmAABtAARmAABtAABmAABtAABm'
    'AAFtAA9mAABtAANmAABtAABmAABtAAxmAABtAABmAABtAAVnAABtAAdnAABtAARnAABtABFnAABtAARn'
    'AABtABBnAABtAAJnAABtAABnAAJtABtnAANtAABnAAJtAARnAABtAANnAAFtAANnAABtABpnAABtAAxn'
    'AABtAAhnAABtABBnAABtAAhnAABtAA5nAABtAABnAABtAAVnAAJtABhnAANtAABnAABtAAlnAABtAABn'
    'AABtAAFnAABtABFnAAFtAAFnAABtAANnAABtAABnAABtAARnAAFtAAJnAABtAANnAABtAANnAABtAAVn'
    'AABtAAFnAABtAAFnAABtAANnAABtAAtnAABtAABnAABtAABnAABtAAVnAABtAANnAAFtAAxnAAZoAABt'
    'ABtoAABtAAhoAABtAABoAABtAAFoAABtAAJoAAFtABVoAABtAAxoAABtAA5oAABtAAFoAABtAAZoAABt'
    'AABoAABtAA5oAABtAAVoAAJtAAFoAABtAAdoAABtAARoAABtAAhoAABtABVoAABtAAloAABtAAJoAAJt'
    'AANoAAFtAAloAABtACFoAAFtAAJoAAFtAABoAABtAAZoAABtAAVoAABtAA1oAANtAAhoAABtAAdoAABt'
    'AAJoAABtABFoAABtAAJoAAFtAAFoAABtABJoAABtAAFoAA9pAABtAAlpAABtAARpAABtAA1pAAxqAAJt'
    'ADtqAABtAB9qAABtAAJqAABtACZqAABtAABqAABtAAJqAABtAAJqAABtAApqAABtAAJqAABtAAdqAABt'
    'AA5qAABtAABqAABtAA5qAABtAAFqAAFtAAJqAABtAAZqAABtAABqAABtAAFqAABtAA9qAABtAAVqAANt'
    'AABqAABtABhqAABtAAVqAAFtAAJqAABtAARqAABtAAdqAABtAChqADVrAANtAABrAABtAAFrAABtAAJr'
    'AABtAAVrAAFtAARrAABtAABrAABtABprAABtAAdrAAFtAAVrAABtAABrAABtAAlrAABtAAFrAAFtAApr'
    'AABtAARrAABtAAJrAAFtAAlrAAJtAAhrAABtAAFrAABtAABrAAFtAA1rAABtAAFrAABtAANrAABtAARr'
    'AAFtAAtrAABtAAJrAABtAAZrAABtAAFrAABtAANrAABtAAFrAABtAAZrAABtAABrAAFtAABrAABtAAFr'
    'AABtABJrAABtAA5rAABtAAFrAABtAAtrAABtAANrAABtAAZrAABtAANrAABtAAZrAAJtAAJrAABtABpr'
    'AAJsAABtAAVsAAFtAAZsAABtAANsAABtABZsAABtABRsAANtAAJsAABtAAdsAABtAANsAABtAAZsAABt'
    'AApsAABtAAFsAABtABZsAAFtAAdsAABtAAxsAABtAARsAABtABFsAABtAAtsAABtABlsAABtAABsAAJt'
    'ABhsAABtAABsAABtAAFsBcYEVrk1OTTGDbgEVgceVgEJVgQBVgBONAEJNAYdVgIFVgpFVgoJVgEGVgEU'
    'VgUSVrADOTQGHV4CCV6WAVpWBRg0Ahg0LEpWBDhWBxBWQAQ0CwY0CfcNNACCEDUAhAI2AP8PNwABBAEC'
    'NwAEOAAABAA0OAABBAC9BTgAAAQAADgAAAQAMTgAAAQADjgAAAQADDgAAAQAHDgAAAQAAjgAAAQAHDgA'
    'AAQAATgAAAQADTgAAAQABTgAAAQAEzgAAAQAAzgAAAQABjgAAAQAAzgAAQQABTgAAAQABzgAAQQAGzgA'
    'AAQABzgAAAQAWjgAAAQAADgAAAQANTgAAAQAATgAAAQACjgAAAQABDgAAAQAFTgAAAQABzgABF4kIThf'
    'cjgNADgACl4AADgAQV4AAAQAAl4AAAQAF14AAAQACl4AADgAGF4AAAQANV4AATgADl4AAjgAAV4AAAQA'
    'BV4AADgAA14AATgAEl4AADgAB14AADgAAF4AADgABV4AADgAAV4AAjgAOF4AADgAF14AAAQAEF4AAAQA'
    'Bl4AAAQAFl4AADgAB14AADgAEV4AAAQAhwFeAAAEAAA4AAdeAAA4ACFeAAA4AABeAAM4AAxeAAEEAC9e'
    'AAAEAEpeAAA4AANeAAA4AENeAAA4AEdeDgAEAAFeAAIEAAA4AABeAAA4AAIEAAI4AAIEAAA4AAEEAAA4'
    'AAEEAAE4AAEEAAA4AAMEAAJeAAA4AAEEAAE4AAAEAAA4AABeAAAEAAA4AAFeAAAEAAA4AAAEnTwDOQEG'
    'OQEBOQGiAjkAAV4AATkAAV4JADkdAjkCADkOAzkAAF4HiwM5hBJqOQUMOQMIOQcJOQIHOdwe/AE6A7MD'
    'OgYWOgECOgggOgItOgIWOglzOjz1AVcKJlcAAToAtAFXACE6AEVXCjE6PhM6DBM6bBFXAAY6hwFUWwFG'
    'WwEBWwIAWwIBWwIDWwELWwEAWwEGWwFAWwEDWwIHWwEGWwEbWwEDWwEEWwEAWwMGWwHTAlsAADoBowJb'
    'AjFbAIsFOg8EOgEOOlAbOgAAXuMHgQE6DgY6NjI6AAY7ARA7AgY7AQE7AQQ7BT07IQA7cCxXAw1XAglX'
    'BAFXwAIeOxE5VwUAV9ADKTvWASo7BAA7wAEeOwEVOwgBO+ABBjsBAzsBATsBDjsBxAE7Ag87KUtbBAlb'
    'BAFbkQZDO0w8V8IBAzsBGjsBATsBADsCADsBCTsBAzsBADsBADsGADsEADsBADsBADsBAjsBATsBADsC'
    'ADsBADsBADsBADsBADsBATsBADsCAzsBBjsBAzsBAzsBADsBCTsBEDsFAjsBBDsBEDs0ATuOAgMEAAAA'
    'ACYEBGNdDA47Ag47AQ07AAAAASQ7CgxSAAI7AFxSAAI7AAEAAAtSAAEAAA1SAAAAAAFSAAkAABFSAAE7'
    'NxkAAABSAAEADQlSAAAAABNSAAAAAAFSAAgAAABSBAhSBwEADgU7mgEhAAABOwBvAAABOwABAAAAOwAC'
    'AAABOwBSAAABOwACAAAAOwCGAgAAADsAPgAACjsABQAAAFcAFwAABjsAAQAAATsABwAACzsAAAAAATsA'
    'AwAAATsAAAAAAzsAAQAADDsAAQAAATsAAAAAADsAAgQAAzsAAQAACDsAAAAABDsAAgAACzsAAgAABzsA'
    'AgAAATsAAAAAADsAAAAAAzsAAAAABTsAAAAAAjsAAAAABTsAVQAALzsARQAABDsABwAAATsAAwAAAF4C'
    'CQAAAjsAAAAAADsAAQADAAAAATsACQADc1cAZzsECwAEAAAAGjsENzsICTsGJzsIHTsCCzsEATsOCDsn'
    'CzsALgAAAFcACQAAAFcAuAEAAFc7CA07AgwAAwoAAAJeADgAAQAAAwBeAA8AAABeAQsAAABeAwkAAAFe'
    'BZIBOwAAXQBmO4UIwA4FAMAOBgDADgcAwA4IAPsFCQDADgoAwA4LAMAODADADg0A+wUOAMAODwDADhAA'
    'wA4RAMAOEgD7BRMAwA4UAMAOFQDADhYAwA4XAPsFGADADhkAwA4aAMAOGwDADhwA+wUdAN8NHiBgHgDA'
    'Dh8AwA4gALsEIQGECiEA2gUiAMAOIwDADiQAKyUClA4lAMAOJgD5BScAwA4oAJ8JKQ/tBCmiEzIpAOoD'
    'KuILghA8AIIQPQDEBj4F2gg+AAAqAGI+AJ0IPwAAKgDNBD8AACoAggM/AIIQQADYAkEAACoAqQ1BAPII'
    'Qoa3AqoBbwCqAXAAqgFxAKoBcgCqAXMAqgF0AKoBdQCqAXYAqgF3AKoBeACqAXkAqgF6AKoBewCqAXwA'
    'qgF9AKoBfgCqAX8AqgGAAQCqAYEBAKoBggEAqgGDAQCqAYQBAKoBhQEAogGGAQCqAYcBAKoBiAEAqgGJ'
    'AQCqAYoBAKoBiwEAqgGMAQCqAY0BAKoBjgEAqgGPAQCqAZABAKoBkQEAqgGSAQCqAZMBAKoBlAEAqgGV'
    'AQCqAZYBAKoBlwEAqgGYAQCqAZkBAKoBmgEAqgGbAQCqAZwBAKoBnQEAqgGeAQCqAZ8BAKoBoAEAqgGh'
    'AQCqAaIBAKoBowEAqgGkAQCqAaUBAKoBpgEAqgGnAQCqAagBAKoBqQEAqgGqAQCqAasBAKoBrAEAqgGt'
    'AQCqAa4BAKoBrwEA3AGwAcGHKABCHg9CAAkAACZCABkAAANCAAAAgAHvAUKZ3AYAXdtpCQC8BgBXAAAA'
    'AQkAyA+VAV0KA10MJV0KZV06BV0aAV0eAF0fAF0PAF2PCv8BXYAIFF0BAF0BEV0CA10BBF0GtQFdBgdd'
    'gAZ/XQMAXQIKXQEBXQMBXQHlAV24jAMZQgQFQgEFQgMIQgEYQg==';
